export const RETAILER_LIST_ADDRESS = 'RETAILER_LIST_ADDRESS';
export const RETAILER_ADD_ADDRESS = 'RETAILER_ADD_ADDRESS';
export const RETAILER_GET_ADDRESS = 'RETAILER_GET_ADDRESS';
export const RETAILER_UPDATE_ADDRESS = 'RETAILER_UPDATE_ADDRESS';
export const RETAILER_DELETE_ADDRESS = 'RETAILER_DELETE_ADDRESS';
export const RETAILER_ADDRESS_RESET = 'RETAILER_ADDRESS_RESET'