export const SALES_LIST_ADDRESS = 'SALES_LIST_ADDRESS';
export const SALES_ADD_ADDRESS = 'SALES_ADD_ADDRESS';
export const SALES_GET_ADDRESS = 'SALES_GET_ADDRESS';
export const SALES_UPDATE_ADDRESS = 'SALES_UPDATE_ADDRESS';
export const SALES_DELETE_ADDRESS = 'SALES_DELETE_ADDRESS';
export const SALES_ADDRESS_RESET = 'SALES_ADDRESS_RESET'