export const LIST_ADDCART = 'LIST_ADDCART';
export const ADD_ADDCART = 'ADD_ADDCART';
export const GET_ADDCART = 'GET_ADDCART';
export const UPDATE_ADDCART = 'UPDATE_ADDCART';
export const DELETE_ADDCART = 'DELETE_ADDCART';
export const RESET_ADDCART = 'RESET_ADDCART';
export const UPDATE_ADDCART_SIZE_MATERIAL = 'UPDATE_ADDCART_SIZE_MATERIAL';
