export const CUSTOMER_LIST_ADDRESS = 'CUSTOMER_LIST_ADDRESS';
export const CUSTOMER_ADD_ADDRESS = 'CUSTOMER_ADD_ADDRESS';
export const CUSTOMER_GET_ADDRESS = 'CUSTOMER_GET_ADDRESS';
export const CUSTOMER_UPDATE_ADDRESS = 'CUSTOMER_UPDATE_ADDRESS';
export const CUSTOMER_DELETE_ADDRESS = 'CUSTOMER_DELETE_ADDRESS';
export const CUSTOMER_ADDRESS_RESET = 'CUSTOMER_ADDRESS_RESET'