export const CUSTOMER_LIST_PRODUCT = 'CUSTOMER_LIST_PRODUCT';
export const CUSTOMER_GET_PRODUCT = 'CUSTOMER_GET_PRODUCT';
export const CUSTOMER_PRODUCT_PROCESSING = 'CUSTOMER_PRODUCT_PROCESSING';
export const CUSTOMER_PRODUCT_WISHLIST_UPDATE = 'CUSTOMER_PRODUCT_WISHLIST_UPDATE';