export const CUSTOMER_LIST_RETAILER = 'CUSTOMER_LIST_RETAILER';
export const CUSTOMER_ADD_RETAILER = 'CUSTOMER_ADD_RETAILER';
export const CUSTOMER_UPDATE_RETAILER = 'CUSTOMER_UPDATE_RETAILER';
export const CUSTOMER_DELETE_RETAILER = 'CUSTOMER_DELETE_RETAILER';
export const CUSTOMER_GET_RETAILER = 'CUSTOMER_GET_RETAILER';
export const CUSTOMER_RESET_RETAILER = 'CUSTOMER_RESET_RETAILER';
export const CUSTOMER_LIST_RETAILER_REVIEW = 'CUSTOMER_LIST_RETAILER_REVIEW';