export const LIST_WISHLIST = 'LIST_WISHLIST';
export const ADD_WISHLIST = 'ADD_WISHLIST';
export const GET_WISHLIST = 'GET_WISHLIST';
export const UPDATE_WISHLIST = 'UPDATE_WISHLIST';
export const DELETE_WISHLIST = 'DELETE_WISHLIST';
export const RESET_WISHLIST = 'RESET_WISHLIST';
export const UPDATE_WISHLIST_COUNT = 'UPDATE_WISHLIST_COUNT';